// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
const path = require("path");
require("dotenv").config(path.resolve(__dirname, "./.env"));
const { defineConfig } = require("prisma/config");

module.exports = defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
